[package]
name = "encoder"
version = "0.1.0"
edition = "2021"
authors = ["Jian Chen <admin@chensoft.com>"]
license = "MIT"
description = "A collection of crates for rapid encoding"
documentation = "https://docs.rs/encoder"
repository = "https://github.com/chensoft/encoder"
readme = "README.md"
keywords = ["encoder", "encode", "encoding"]

[dependencies]
itoa = {path = "lib/itoa-1.0.10"}